# Generated by Django 5.2.8 on 2025-12-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=500)),
                ("address", models.CharField(blank=True, default="", max_length=500)),
                ("image_url", models.URLField(blank=True, default="")),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("score", models.IntegerField(default=0)),
                ("nearby_activities", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
