# Generated by Django 5.2.8 on 2026-02-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TourismPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_id", models.BigIntegerField(unique=True)),
                ("content_type_id", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("addr1", models.CharField(blank=True, max_length=255)),
                ("addr2", models.CharField(blank=True, max_length=255)),
                ("zipcode", models.CharField(blank=True, max_length=20)),
                ("tel", models.CharField(blank=True, max_length=100)),
                ("homepage", models.TextField(blank=True)),
                ("area_code", models.CharField(blank=True, max_length=20)),
                ("sigungu_code", models.CharField(blank=True, max_length=20)),
                ("cat1", models.CharField(blank=True, max_length=20)),
                ("cat2", models.CharField(blank=True, max_length=20)),
                ("cat3", models.CharField(blank=True, max_length=20)),
                (
                    "mapx",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=12, null=True
                    ),
                ),
                (
                    "mapy",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=12, null=True
                    ),
                ),
                ("first_image", models.URLField(blank=True, max_length=500)),
                ("first_image2", models.URLField(blank=True, max_length=500)),
                ("overview", models.TextField(blank=True)),
                ("source_modified_time", models.CharField(blank=True, max_length=30)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type_id"],
                        name="places_tour_content_2538bd_idx",
                    ),
                    models.Index(
                        fields=["area_code", "sigungu_code"],
                        name="places_tour_area_co_d415cb_idx",
                    ),
                    models.Index(
                        fields=["cat1", "cat2", "cat3"],
                        name="places_tour_cat1_d48292_idx",
                    ),
                ],
            },
        ),
    ]
