# Generated by Django 5.2.8 on 2026-03-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tourismplace",
            index=models.Index(
                fields=["mapx", "mapy"], name="places_tour_mapx_ebf760_idx"
            ),
        ),
    ]
