# Generated by Django 5.2.8 on 2026-04-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_tourismplace_places_tour_mapx_ebf760_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourismplace",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="tourismplace",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="tourismplace",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="tourismplace",
            name="region_category_key",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="tourismplace",
            name="thumbnail_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name="tourismplace",
            index=models.Index(
                fields=["region_category_key"], name="places_tour_region__0f4b81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tourismplace",
            index=models.Index(
                fields=["latitude", "longitude"], name="places_tour_latitud_17ab0a_idx"
            ),
        ),
    ]
