# Generated by Django 5.2.8 on 2026-04-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_backfill_tourismplace_location_and_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourismplace",
            name="category_key",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="tourismplace",
            name="category_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="tourismplace",
            index=models.Index(
                fields=["category_key"], name="places_tour_categor_718148_idx"
            ),
        ),
    ]
