# Generated by Django 5.2.13 on 2026-05-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_backfill_place_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismplace',
            name='keyword_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
